[DB]
USER=tkalychmaksim_db_user
PASS=Kay4cW3xipsT1PsI
DB_NAME=nosql_homework
DOMAIN=cluster0.6xlcd5w.mongodb.net
#mongodb+srv://tkalychmaksim_db_user:<db_password>@cluster0.6xlcd5w.mongodb.net/?appName=Cluster0